version: "2.1"

services:
    training-partner:
        build: ./src/
        restart: always
        ports:
            - 8111:8000
        env_file:
            - ./app.env
        volumes:
            - './media/:/usr/src/app/media/'
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mariadb:10.8.2
        restart: always
        ports:
            - 3307:3306
        env_file:
            - ./db.env
        volumes:
            - './mariadb/:/var/lib/mysql/'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
            interval: 30s
            timeout: 10s
            retries: 20