# Generated by Django 4.0 on 2022-12-10 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('personNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('reps', models.PositiveIntegerField()),
                ('exerciseNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workoutplan.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('equipments', models.ManyToManyField(to='workoutplan.EquipmentBase')),
                ('muscles', models.ManyToManyField(to='workoutplan.MuscleBase')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exerciseBaseNr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutplan.exercisebase'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workoutNr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workoutplan.workout'),
        ),
    ]
