# Generated by Django 4.0.6 on 2023-03-20 10:38

from django.db import migrations, models
import workoutplan.models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisebase',
            name='picture',
            field=models.ImageField(null=True, upload_to=workoutplan.models.uploadExercisePic),
        ),
    ]
