# Generated by Django 4.0 on 2022-12-10 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('height', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kg', models.FloatField()),
                ('personNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='BodyOptic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('front', models.ImageField(null=True, upload_to=person.models.uploadBodyPic)),
                ('frontFlex', models.ImageField(null=True, upload_to=person.models.uploadBodyPic)),
                ('side', models.ImageField(null=True, upload_to=person.models.uploadBodyPic)),
                ('sideFlex', models.ImageField(null=True, upload_to=person.models.uploadBodyPic)),
                ('back', models.ImageField(null=True, upload_to=person.models.uploadBodyPic)),
                ('backFlex', models.ImageField(null=True, upload_to=person.models.uploadBodyPic)),
                ('personNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optics', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='BodyFat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('point1', models.FloatField()),
                ('point2', models.FloatField()),
                ('point3', models.FloatField()),
                ('point4', models.FloatField()),
                ('point5', models.FloatField()),
                ('point6', models.FloatField()),
                ('point7', models.FloatField()),
                ('kfa', models.FloatField(default=0)),
                ('personNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fats', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='BodyDimension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('breast', models.FloatField()),
                ('arm', models.FloatField()),
                ('stomach', models.FloatField()),
                ('hip', models.FloatField()),
                ('upperLeg', models.FloatField()),
                ('lowerLeg', models.FloatField()),
                ('personNr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='person.person')),
            ],
        ),
    ]
